import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
import Header from "./components/Header";
import { Exo_2 } from 'next/font/google';



const exo2 = Exo_2({ weight: ['400'], subsets: ['latin'] });
=======
>>>>>>> fa12ac952d53caac952ef6f30bdeb5bad4e884c8

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Muhamad Huzaifa - Developer ",
=======
  title: "Create Next App",
>>>>>>> fa12ac952d53caac952ef6f30bdeb5bad4e884c8
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${exo2.className}`}
      >
        <Header/>
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
>>>>>>> fa12ac952d53caac952ef6f30bdeb5bad4e884c8
        {children}
      </body>
    </html>
  );
}
